"""Initial telemetry table

Revision ID: 1f19d1108737
Revises: 
Create Date: 2026-04-21 19:25:43.722853

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision: str = '1f19d1108737'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('phone_telemetry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('accel_x', sa.Float(), nullable=False),
    sa.Column('accel_y', sa.Float(), nullable=False),
    sa.Column('accel_z', sa.Float(), nullable=False),
    sa.Column('geom', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # op.create_index('idx_phone_telemetry_geom', 'phone_telemetry', ['geom'], unique=False, postgresql_using='gist')
    op.create_index(op.f('ix_phone_telemetry_id'), 'phone_telemetry', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_phone_telemetry_id'), table_name='phone_telemetry')
    op.drop_index('idx_phone_telemetry_geom', table_name='phone_telemetry', postgresql_using='gist')
    op.drop_table('phone_telemetry')
    # ### end Alembic commands ###
