"""add role to users

Revision ID: 88074f50fc93
Revises: 316714b0c67b
Create Date: 2026-05-23 09:05:12.658974

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '88074f50fc93'
down_revision: Union[str, Sequence[str], None] = '316714b0c67b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    user_role_enum = sa.Enum('user', 'demo', 'admin', name='user_role')
    user_role_enum.create(op.get_bind())

    # Крок 2: потім додаємо колонку
    op.add_column('users', sa.Column(
        'role',
        user_role_enum,
        server_default='user',
        nullable=False,
    ))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'role')
    # ### end Alembic commands ###
    op.execute("DROP TYPE IF EXISTS user_role") 
